/*Generated by WaveMaker Studio*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class InsertQuesryEmployeeRequest implements Serializable {


    @JsonProperty("EMP_ID")
    private Integer empId;

    @JsonProperty("LASTNAME")
    private String lastname;

    @JsonProperty("FIRSTNAME")
    private String firstname;

    @JsonProperty("USERNAME")
    private String username;

    @JsonProperty("PASSWORD")
    private String password;

    @JsonProperty("STREET")
    private String street;

    @JsonProperty("CITY")
    private String city;

    @JsonProperty("STATE")
    private String state;

    @JsonProperty("ZIP")
    private String zip;

    @JsonProperty("BIRTHDATE")
    private Date birthdate;

    @JsonProperty("TENANT_ID")
    private Integer tenantId;

    public Integer getEmpId() {
        return this.empId;
    }

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public Date getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public Integer getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof InsertQuesryEmployeeRequest)) return false;
        final InsertQuesryEmployeeRequest insertQuesryEmployeeRequest = (InsertQuesryEmployeeRequest) o;
        return Objects.equals(getEmpId(), insertQuesryEmployeeRequest.getEmpId()) &&
                Objects.equals(getLastname(), insertQuesryEmployeeRequest.getLastname()) &&
                Objects.equals(getFirstname(), insertQuesryEmployeeRequest.getFirstname()) &&
                Objects.equals(getUsername(), insertQuesryEmployeeRequest.getUsername()) &&
                Objects.equals(getPassword(), insertQuesryEmployeeRequest.getPassword()) &&
                Objects.equals(getStreet(), insertQuesryEmployeeRequest.getStreet()) &&
                Objects.equals(getCity(), insertQuesryEmployeeRequest.getCity()) &&
                Objects.equals(getState(), insertQuesryEmployeeRequest.getState()) &&
                Objects.equals(getZip(), insertQuesryEmployeeRequest.getZip()) &&
                Objects.equals(getBirthdate(), insertQuesryEmployeeRequest.getBirthdate()) &&
                Objects.equals(getTenantId(), insertQuesryEmployeeRequest.getTenantId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpId(),
                getLastname(),
                getFirstname(),
                getUsername(),
                getPassword(),
                getStreet(),
                getCity(),
                getState(),
                getZip(),
                getBirthdate(),
                getTenantId());
    }
}
