/*Generated by WaveMaker Studio*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class InsertQuesryVacationRequest implements Serializable {


    @JsonProperty("ID")
    private Integer id;

    @JsonProperty("START_DATE")
    private Date startDate;

    @JsonProperty("END_DATE")
    private Date endDate;

    @JsonProperty("EMP_ID")
    private Integer empId;

    @JsonProperty("TENANT_ID")
    private Integer tenantId;

    @JsonProperty("STATUS")
    private String status;

    @JsonProperty("TYPECol")
    private String typecol;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Integer getEmpId() {
        return this.empId;
    }

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    public Integer getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getTypecol() {
        return this.typecol;
    }

    public void setTypecol(String typecol) {
        this.typecol = typecol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof InsertQuesryVacationRequest)) return false;
        final InsertQuesryVacationRequest insertQuesryVacationRequest = (InsertQuesryVacationRequest) o;
        return Objects.equals(getId(), insertQuesryVacationRequest.getId()) &&
                Objects.equals(getStartDate(), insertQuesryVacationRequest.getStartDate()) &&
                Objects.equals(getEndDate(), insertQuesryVacationRequest.getEndDate()) &&
                Objects.equals(getEmpId(), insertQuesryVacationRequest.getEmpId()) &&
                Objects.equals(getTenantId(), insertQuesryVacationRequest.getTenantId()) &&
                Objects.equals(getStatus(), insertQuesryVacationRequest.getStatus()) &&
                Objects.equals(getTypecol(), insertQuesryVacationRequest.getTypecol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getStartDate(),
                getEndDate(),
                getEmpId(),
                getTenantId(),
                getStatus(),
                getTypecol());
    }
}
