/*Generated by WaveMaker Studio*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class InsertQueryUserRequest implements Serializable {


    @JsonProperty("USERNAME")
    private String username;

    @JsonProperty("PASSWORD")
    private String password;

    @JsonProperty("ROLE")
    private String role;

    @JsonProperty("TENANT_ID")
    private Integer tenantId;

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Integer getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof InsertQueryUserRequest)) return false;
        final InsertQueryUserRequest insertQueryUserRequest = (InsertQueryUserRequest) o;
        return Objects.equals(getUsername(), insertQueryUserRequest.getUsername()) &&
                Objects.equals(getPassword(), insertQueryUserRequest.getPassword()) &&
                Objects.equals(getRole(), insertQueryUserRequest.getRole()) &&
                Objects.equals(getTenantId(), insertQueryUserRequest.getTenantId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUsername(),
                getPassword(),
                getRole(),
                getTenantId());
    }
}